### ISSUE TITLE
Why not use this.forEach within nodeList.on and nodeList.trigger?

### ISSUE THREAD

**Issue by joncasey** [remy/min.js#11]
Not really an issue, but wasn't sure where I could pass this along?
If you are only var'ing the "each" to use within the NodeList protototype addons, why not just declare it, and then actually use it?

``` javascript
var list = NodeList.prototype

list.forEach = Array.prototype.forEach

list.on = function(e, fn) {
  this.forEach(function(el) { el.on(e, fn) })
  return this
}

list.trigger = function(e) {
  this.forEach(function(el) { el.trigger(e) })
  return this
}
```

**Comment by remy** [comment]
Yep, not sure why I didn't spot this before, compresses smaller too :)
