### ISSUE TITLE
Don't use NodeList.__proto__

### ISSUE THREAD

**Issue by simevidas** [remy/min.js#14]
This is based on our [Twitter discussion](https://twitter.com/simevidas/status/355489560383340544).

The problematical code: 

```
nodeList = NodeList.__proto__ || NodeList.prototype
```

and then

```
nodeList[forEach] = each;
```

`NodeList.__proto__` shouldn't be used. In Chrome, it refers to `Object.prototype` (!!) and in Firefox it refers to some "magical" host object. So, in Chrome you're adding a `forEach` property to `Object.prototype`, i.e. you're extending `Object.prototype`. You're doing this unintentionally, but even if you were doing this on purpose, it would be an awful approach.

From what I see, your intent is to be able to iterate over `NodeList` instances. The standard approach would be to extend `NodeList` prototype:

```
NodeList.prototype.forEach = Array.prototype.forEach;
```

But you're already doing the iteration differently by invoking `Array.prototype.forEach` via `call()` like so:

```
each.call(this, function (el) {
  el.on(event, fn);
});
```

This is a good approach. It gets the job done just fine. Therefore, you don't need to add a `forEach` method to `NodeList.prototype` and the two lines of code (from the beginning of my message) should be removed. (Edit: Only the second line should be removed. The first line is need to add stuff to `Node.prototype`. See my pull request.)

**Comment by simevidas** [comment]
And the pull request: https://github.com/remy/min.js/pull/15

**Comment by remy** [comment]
Cheers for the issue & pull. Definitely not my intention to crud with object.proto! I also need to make more tests that are a little fuller!

**Comment by remy** [comment]
Right, just read your code and comment fully (I was out when I got the pull request).

I'm adding the `forEach` as a helper util on the return value from a qSA call - so the developer can do `$('.foo').forEach(fn)`.

So your change is basically a revert on my use of `__proto__` - which having read your explanation is definitely something I need.  But, it means that `$('failed_selector').on('foo', fn)` breaks in Firefox...which is why I used `__proto__` in the first place.

Maybe drawing board again, maybe consider Firefox support..?

**Comment by remy** [comment]
Sorted it. I can't remember why I was returning the `nodeList` on an empty selector, but returning the value of the empty selector https://github.com/remy/min.js/blob/master/src/%24.js#L60 means that Firefox has an instantiated `NodeList` object, and the tests pass just fine.

**Comment by simevidas** [comment]
Cool. 

It's a bit weird though that inside the `.on` callbacks, `this` is used to refer to the individual elements, whereas inside the `.forEach` callbacks one has to define a parameter to get a reference to the individual elements. E.g. 

```
var divList = $('div');

divList.on('click', function () {
    this // the current DIV element
});

divList.forEach(function (div) {
    this // does *not* refer to the current DIV element
    div // the current DIV element
});
```

jQuery normalizes this, so that you can refer to the current element via `this` in pretty much all jQuery callbacks. 

Btw, I've [tested a bit](http://jsfiddle.net/simevidas/y8s2Y/) in Firefox. Everything seems to work.

**Comment by simevidas** [comment]
If you want to normalize the `this` value inside `.forEach`, it can be done like so:

```
NodeList.prototype.forEach = function (callback) {
    each.call(this, function (elem, i) {
        callback.apply(elem, [elem, i]);
    });
};
```

**Live demo:** http://jsfiddle.net/simevidas/A6gCG/
